### ISSUE TITLE
Smaart V9

### ISSUE THREAD

**Issue by RoelJHengeveld** [bitfocus/companion-module-rationalacoustics-smaart3#2]
Hi! First of all many thanks for the work you have put into this instance of Companion. I'm a huge fan and it helpt improving my workflow and speeding up the process of system tuning a lot.

By the end of September Rational Acoustics released their V9 of Smaart. I'm really looking forward to work with this version of Smaart and bought it right away as it was released. I soon discovered that a lot my beloved Stream Deck programs do not work anymore with Smaart V9. So I'm wondering if there is any plan of releasing an instance on Companion for Smaart V9 in the future? If I can be of any help in the development I'm happy to help!

Have a nice day!

Roel

**Comment by murphytodd4** [comment]
I was just sent the updated API document. I will try and find some time to implement the changes that happened with API V4. It may be a little bit before I can get that done though.

**Comment by RoelJHengeveld** [comment]
Hi!

Sorry for my late reply, but just wanted to tell you I really appreciate your efforts! Looking forward to work with the update. For now I stick with Smaart V8.


Have a nice day!



Hartelijke groet,


Roel Hengeveld    |  Sound Everest
Soundeverest.eu  |  +31 6 11 86 33 88

**Comment by murphytodd4** [comment]
I have the majority of this updated now. I ran into a few issues (mostly just bugs with Smaart V9) I have contacted Rational Acoustics and once they have answers for me I will get a module and have it added to the core. I need to start a conversation about it with the devs but its likely going to be a new module since they did make the new API non backwards compatible and the API version is in the module title.

**Comment by RoelJHengeveld** [comment]
That sounds awesome. Yeah unfortunately Smaart V9 is quit buggy for the moment.



Hartelijke groet,


Roel Hengeveld    |  Sound Everest
Soundeverest.eu  |  +31 6 11 86 33 88

**Comment by glp-66** [comment]
Any updates on this? Thanks for the effort and all you do for companion!

**Comment by murphytodd4** [comment]
This issue is going to be closed. The module to interface with V4 of their API is now in the core. The V4 module has some limitations due to the removal of some API options though.
